scan_timeout = 30
add_newline = false

[line_break]
disabled = true

[directory]
style = "bold blue"

[cmd_duration]
format = "[$duration]($style) "

[status]
disabled = false
format = "[$symbol $status]($style) "
not_found_symbol = "ï€"
not_executable_symbol = "ï‘®"
sigint_symbol = "ï­¦"
map_symbol = true

[git_branch]
format = "[$symbol$branch]($style) "

[package]
format = "[$symbol$version]($style) "
symbol = "ï£– "

[python]
python_binary = ["./venv/bin/python", "python", "python3", "python2"]

[docker_context]
format = "via [ğŸ‹ $context](blue bold)"
